#region Header
/**************************************************************************
* First Notice Systems
* 95 Wells Avenue
* Newton, MA 02459
* (617) 886-2600
*
* Proprietary Source Code -- Distribution restricted
*
* Copyright (c) 2007 by First Notice Systems
**************************************************************************/
/* $Header: /SourceCode/Components/FNS2005/DbClassLibrary/AutoModelRecord.cs 5     7/13/10 11:39a Gwynnj $ */
#endregion

using System;
using System.Data;
using System.Runtime.InteropServices;

namespace DbClassLibrary
{
	/// <summary>
	/// Encapsulates the AUTO_MODEL table for eSurance
	/// </summary>
	[ComVisible(false)]
	public class AutoModelRecord : ActiveRecord
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="AutoMakeRecord"/> class.
		/// </summary>
		public AutoModelRecord(): base("AUTO_MODEL")
		{
			// Begin AutoGenerated Column Definitions
			columns.Add(new Column("AUTO_MODEL_ID", String.Empty, "NUMBER"));
			columns.Add(new Column("MAKE_CODE", String.Empty, "VARCHAR2"));
			columns.Add(new Column("MODEL_CODE", String.Empty, "VARCHAR2"));
			columns.Add(new Column("MODEL_DESCRIPTION", String.Empty, "VARCHAR2"));
		}
		/// <summary>
		/// Initializes a new instance of the <see cref="AutoModelRecord"/> class.
		/// </summary>
		/// <param name="reader">The reader.</param>
		public AutoModelRecord(IDataReader reader)
			: base(reader, "AUTO_MODEL")
		{}
		#region AutoModelId
		/// <summary>
		/// Gets or sets the auto model id.
		/// </summary>
		/// <value>The auto model id.</value>
		public string AutoModelId
		{
			get
			{
				return GetColumnValue("AUTO_MODEL_ID");
			}
			set
			{
				SetColumnValue("AUTO_MODEL_ID", value);
			}
		}
		#endregion
		#region MakeCode
		/// <summary>
		/// Gets or sets the make code.
		/// </summary>
		/// <value>The make code.</value>
		public string MakeCode
		{
			get
			{
				return GetColumnValue("MAKE_CODE");
			}
			set
			{
				SetColumnValue("MAKE_CODE", value);
			}
		}
		#endregion
		#region ModelCode
		/// <summary>
		/// Gets or sets the model code.
		/// </summary>
		/// <value>The model code.</value>
		public string ModelCode
		{
			get
			{
				return GetColumnValue("MODEL_CODE");
			}
			set
			{
				SetColumnValue("MODEL_CODE", value);
			}
		}
		#endregion
		#region ModelDescription
		/// <summary>
		/// Gets or sets the model description.
		/// </summary>
		/// <value>The model description.</value>
		public string ModelDescription
		{
			get
			{
				return GetColumnValue("MODEL_DESCRIPTION");
			}
			set
			{
				SetColumnValue("MODEL_DESCRIPTION", value);
			}
		}
		#endregion
	}
}
#region Log
/*
 * $Log: /SourceCode/Components/FNS2005/DbClassLibrary/AutoModelRecord.cs $
 * 
 * 5     7/13/10 11:39a Gwynnj
 * Removed ColumnMap and refactored to ColumnList class to manage
 * multi-key indexing
 * 
 * 4     9/15/09 5:01p John.gwynn
 * Created Import folder and moved Froi classes for further refinement and
 * generalization.  Also resharper reformatting 
 * 
 * 
 * 
 * 
 * 
 * 
 * 3     5/26/09 11:05a John.gwynn
 * Added interop definitions
 * 
 * 2     10/01/07 12:08p John.gwynn
 * 
 * 1     9/27/07 8:57p John.gwynn
 * Added AutoMake and AutoModel Records
  */
#endregion