#region Header
/**************************************************************************
* First Notice Systems
* 95 Wells Avenue
* Newton, MA 02459
* (617) 886-2600
*
* Proprietary Source Code -- Distribution restricted
*
* Copyright (c) 2008 by First Notice Systems
**************************************************************************/
/* $Header: /SourceCode/Components/FNS2005/DbClassLibrary/SessionData.cs 5     7/13/10 11:39a Gwynnj $ */
#endregion

using System;
using System.Data;

namespace DbClassLibrary
{
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.InteropServices.ComVisible(false)]
	public class SessionData : ActiveRecord
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="SessionData"/> class.
		/// </summary>
		public SessionData()
			: base("SESSION_DATA")
		{
			// Begin AutoGenerated Column Definitions
			columns.Add(new Column("SESSION_KEY", String.Empty, "VARCHAR2"));
			columns.Add(new Column("NAME", String.Empty, "VARCHAR2"));
			columns.Add(new Column("VALUE", String.Empty, "VARCHAR2"));
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="SessionData"/> class.
		/// </summary>
		/// <param name="reader">The reader.</param>
		public SessionData(IDataReader reader)
			: base(reader, "SESSION_DATA")
		{ }

		#region SessionKey
		/// <summary>
		/// Gets or sets the session key.
		/// </summary>
		/// <value>The session key.</value>
		public string SessionKey
		{
			get
			{
				return GetColumnValue("SESSION_KEY");
			}
			set
			{
				SetColumnValue("SESSION_KEY", value);
			}
		}
		#endregion

		#region SessionName
		/// <summary>
		/// Gets or sets the name of the session.
		/// </summary>
		/// <value>The name of the session.</value>
		public string SessionName
		{
			get
			{
				return GetColumnValue("NAME");
			}
			set
			{
				SetColumnValue("NAME", value);
			}
		}
		#endregion

		#region SessionValue
		/// <summary>
		/// Gets or sets the session value.
		/// </summary>
		/// <value>The session value.</value>
		public string SessionValue
		{
			get
			{
				return GetColumnValue("VALUE");
			}
			set
			{
				SetColumnValue("VALUE", value);
			}
		}
		#endregion

		/// <summary>
		/// Generates the update SQL.
		/// </summary>
		/// <returns></returns>
		protected override string GenerateUpdateSql()
		{
			return string.Format("update SESSION_DATA set VALUE = '{0}' where SESSION_KEY = '{1}' and NAME = '{2}'",
													 SessionValue, SessionKey, SessionName);
		}

		/// <summary>
		/// Updates the session data.
		/// </summary>
		/// <param name="key">The key.</param>
		/// <param name="name">The name.</param>
		/// <param name="value">The value.</param>
		/// <returns></returns>
		public static bool UpdateSessionData(string key, string name, string value)
		{
			SessionData data = new SessionData();
			data.SessionKey = key;
			data.SessionName = name;
			data.SessionValue = value;
			return data.Update();
		}

		/// <summary>
		/// Inserts the session data.
		/// </summary>
		/// <param name="key">The key.</param>
		/// <param name="name">The name.</param>
		/// <param name="value">The value.</param>
		/// <returns></returns>
		public static bool InsertSessionData(string key, string name, string value)
		{
			SessionData data = new SessionData();
			data.SessionKey = key;
			data.SessionName = name;
			data.SessionValue = value;
			return data.Insert();
		}
	}
}
