#region Header
/**************************************************************************
* First Notice Systems
* 95 Wells Avenue
* Newton, MA 02459
* (617) 886-2600
*
* Proprietary Source Code -- Distribution restricted
*
* Copyright (c) 2007 by First Notice Systems
**************************************************************************/
/* $Header: /SourceCode/Components/FNS2005/DbClassLibrary/UsState.cs 4     7/13/10 11:39a Gwynnj $ */
#endregion

using System;
using System.Data;

namespace DbClassLibrary
{

	/// <summary>
	/// represents a state name and code for custom lookups
	/// </summary>
	[System.Runtime.InteropServices.ComVisible(false)]
	public class UsState : ActiveRecord
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="UsState"/> class.
		/// </summary>
		public UsState() : base("US_STATE")
		{
			// Begin AutoGenerated Column Definitions
			columns.Add(new Column("STATE_CODE", String.Empty, "VARCHAR2"));
			columns.Add(new Column("DESCRIPTION", String.Empty, "VARCHAR2"));
		}
		/// <summary>
		/// Initializes a new instance of the <see cref="UsState"/> class.
		/// </summary>
		/// <param name="reader">The reader.</param>
		public UsState(IDataReader reader)
			: base(reader, "US_STATE")
		{ }
		#region StateCode
		/// <summary>
		/// Gets or sets the state code.
		/// </summary>
		/// <value>The state code.</value>
		public string StateCode
		{
			get
			{
				return GetColumnValue("STATE_CODE");
			}
			set
			{
				SetColumnValue("STATE_CODE", value);
			}
		}
		#endregion
		#region StateName
		/// <summary>
		/// Gets or sets the name of the state.
		/// </summary>
		/// <value>The name of the state.</value>
		public string StateName
		{
			get
			{
				return GetColumnValue("DESCRIPTION");
			}
			set
			{
				SetColumnValue("DESCRIPTION", value);
			}
		}
		#endregion
	}
}
#region Log
/*
 * $Log: /SourceCode/Components/FNS2005/DbClassLibrary/UsState.cs $
 * 
 * 4     7/13/10 11:39a Gwynnj
 * Removed ColumnMap and refactored to ColumnList class to manage
 * multi-key indexing
 * 
 * 3     9/15/09 5:01p John.gwynn
 * Created Import folder and moved Froi classes for further refinement and
 * generalization.  Also resharper reformatting 
 * 
 * 
 * 
 * 
 * 
 * 
 * 2     5/26/09 11:05a John.gwynn
 * Added interop definitions
 * 
 * 1     10/30/07 7:14p John.gwynn
 * ActiveRecordSet now sets instance on record instantiation.  Added
 * support for Evaluation of dynamic Business rules (see RuleRecordSet)
 * and added UsStates for eSurance dropdowns
 */
#endregion