CREATE OR REPLACE FUNCTION FNSOWNER.ENC_VARCHAR (V_VARCHAR IN VARCHAR2)
   RETURN RAW
IS
   V_ENC_VARCHAR   RAW(500);
   V_KEY           RAW(32) := '5A1C39B1603FC65E1AC6AD4A1B3D257AAE23B2EFFD113B3CA8DA1CA5EF4A6169';
   V_MOD           NUMBER
      :=   SYS.DBMS_CRYPTO.ENCRYPT_AES
         + SYS.DBMS_CRYPTO.CHAIN_CBC
         + SYS.DBMS_CRYPTO.PAD_PKCS5;
BEGIN
   V_ENC_VARCHAR :=
      SYS.DBMS_CRYPTO.ENCRYPT (UTL_RAW.CAST_TO_RAW (V_VARCHAR), V_MOD, V_KEY);
   RETURN V_ENC_VARCHAR;
END;
/
CREATE OR REPLACE FUNCTION FNSOWNER.DEC_VARCHAR (V_RAW IN RAW)
   RETURN VARCHAR2
IS
   V_RET       VARCHAR2 (500);
   V_KEY       RAW(32) := '5A1C39B1603FC65E1AC6AD4A1B3D257AAE23B2EFFD113B3CA8DA1CA5EF4A6169';
   V_DEC_RAW   RAW (500);
   V_MOD       NUMBER
      :=   DBMS_CRYPTO.ENCRYPT_AES
         + DBMS_CRYPTO.CHAIN_CBC
         + DBMS_CRYPTO.PAD_PKCS5;
BEGIN
   V_DEC_RAW := DBMS_CRYPTO.DECRYPT (V_RAW, V_MOD, V_KEY);
   V_RET := UTL_RAW.CAST_TO_VARCHAR2 (V_DEC_RAW);
   RETURN V_RET;
END;
/
